### PR TITLE
Adds prev next fix

### PR DESCRIPTION
**Pull request by clausmullie**
Adds the fix originally proposed in #1 by re-reverting commits that I reverted in #2 in order to create two separate pull requests, one for branding changes and one for this fix. 

@jgroenen - sorry for creating a soup, this was my first time working with reverts. Can you review that these were the changes you intended? 

And thanks @ericherman for helping me get untangled! :smile:

### CODE REVIEW

**Comment by ericherman** [comment]
When I looked at this myself, I wasn't 100% confident that reverting those two commits would be enough.

I created a draft-PR ( #11 ) to illustrate what I thought might be missing.
In particular, I couldn't tell for certain if the work originally in commit 7dff70b4f9abed720ba8fc0604347be15a0efe3b was properly included.

**Comment by ericherman** [comment]
@jgroenen - can you please look at and test this PR ( or maybe my draft #11 ) to see if this fully includes the work you intended in PR #1 ?

**Comment by jgroenen** [comment]
Hi @ericherman yes, I checked this code against https://github.com/codefornl/standard-for-public-code-jekyll-theme which I am using right now for https://codefor.nl/community-translations-standard/nl/ and these are the relevant changes. What I cannot check is if it will lead to problems in other places, since I don't know all the places where the theme is used. I don't expect this, but this solution does depend on urls being in a certain way and "translation-title" not being defined in other places.

**Comment by ericherman** [comment]
> I checked this code against https://github.com/codefornl/standard-for-public-code-jekyll-theme which I am using right now for https://codefor.nl/community-translations-standard/nl/ and these are the relevant changes.

Good. Then @clausmullie, if you test it with the english version and it all works, then I think that it makes sense to merge this.

**Comment by clausmullie** [comment]
Right, so I pulled both the theme and the community translations and did some testing. 

I can reproduce the error that with the current theme both the Spanish and Traditional Chinese criteria appear as nav.

However, when I pulled in this fix, the Spanish version doesn't have the Traditional Chinese criteria (so there it works), but the Traditional Chinese index was missing all criteria and no prev/next list is generated, so something breaks there.

**Comment by clausmullie** [comment]
With the criteria pages on da and zh translations now working with the current theme, I tested this fix and can confirm it works. Prev/next is shown in the right language only, and all translations have their own criteria page. 

I did notice es and da display a list of all criteria on their index.md, and the zh translation just lists the 'criteria' parent folder without a list of individual criteria below it, but that's a separate issue. 

Good to go!

**Pull request merged**
