### PR TITLE
Fix problem with multiple prev next links

### PR DESCRIPTION
**Pull request by jgroenen**
In the community translations there was a problem, in which the criterium pages showed multiple prev next links, because there where multiple folders (language folders) containing criteria (pages having "order" attribute).
This fix checks if there is a url section before "/criteria/", which is the case for community translations (the language iso code folder is before the "/criteria/" section, e.g. "/nl/criteria/"), then filtering the criteria pages on having that iso code in the url.

### CODE REVIEW

**Comment by ericherman** [comment]
I see that this PR has a lot of overlap with @clausmullie 's PR. Like that PR, I think we should split them into branding and prev-next fixes.

**Comment by ericherman** [comment]
Since there was so much over-lap, rebasing this work on the latest may be a bit tricky. If needed, I can help with that.

**Comment by clausmullie** [comment]
Curious, I merged #8 and it merged this one as well - is this something worth undoing for correct form, or can we leave as is?

**Comment by clausmullie** [comment]
I see the prev next commits were not included, so a new pull request should be made for just those

**Comment by jgroenen** [comment]
Sorry, I bundled two issues in a single pull request; not the best practice :(

**Pull request merged**
